# Using RandomForestClassifier

In [52]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [53]:
gesture_folder_path = "Gesture" 

In [54]:
# Read CSV files into DataFrames and concatenate them into a single DataFrame
def load_csv_to_df(file_path_str):
    dfs = []
    for label in range(1, 6):
        folder_path = f"{gesture_folder_path}/{label}"
        for file_name in os.listdir(folder_path):
                if not file_name.startswith('.'): 
                    file_path = f"{folder_path}/{file_name}"
                    df = pd.read_csv(file_path)
                    df["Person"] = label
                    dfs.append(df)
    df = pd.concat(dfs)
    return df
df.tail()

Timestamp    AccelX    AccelY    AccelZ     GyroX     GyroY  \
2851  150826668708568 -0.280122  3.538630  8.052000  1.331534 -0.940274   
2852  150826670708368 -0.280122  3.538630  8.052000  1.331534 -0.940274   
2853  150826670708368 -0.280122  3.538630  8.052000  1.335810 -0.978148   
2854  150826672708168 -0.289698  3.550601  8.011298  1.335810 -0.978148   
2855  150826672708168 -0.289698  3.550601  8.011298  1.338864 -0.995863   

         GyroZ  Person  
2851  0.085063       5  
2852  0.085063       5  
2853  0.085674       5  
2854  0.085674       5  
2855  0.082620       5

In [55]:
# Split data into features and labels
X = df.drop(["Person", "Timestamp"], axis=1)  # Drop "Person" and "Timestamp" columns as features
y = df["Person"]  # Use "Person" column as labels

In [56]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
# Initialize Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [58]:
# Predict on test data
y_pred = clf.predict(X_test)

# Calculate accuracy and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

# Print accuracy and confusion matrix
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion_mat)

Accuracy: 0.9993321421453273
Confusion Matrix:
 [[56606    34     0     3     7]
 [   75 56929     2     4     4]
 [    0     0 57555     4    15]
 [    0     0     4 57060    11]
 [   10     0     4    14 57648]]


In [ ]:
def load_csv_to_df_knn(file_path_str):
    X = []
    y =[]
    for label in range(1, 6):
        folder_path = f"{gesture_folder_path}/{label}"
        for file_name in os.listdir(folder_path):
                if not file_name.startswith('.'): 
                    file_path = f"{folder_path}/{file_name}"
                    df = pd.read_csv(file_path)
                    X.append(df.drop("Timestamp", axis=1))  # "Timestamp" is not a feature
                    y.append(label)
    return X, y

In [ ]:
def load_csv_to_list(file_path_str):
    X = []
    y =[]
    for label in range(1, 6):
        folder_path = f"{gesture_folder_path}/{label}"
        for file_name in os.listdir(folder_path):
                if not file_name.startswith('.'): 
                    file_path = f"{folder_path}/{file_name}"
                    df = pd.read_csv(file_path)
                    X.append(df.drop(["Timestamp"], axis=1).values)  # "Timestamp" is not a feature
                    y.append(label)
    return X, y